### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by fabry76** [netscaler/ADC-scripts#19]
The Readme file has a typo in the section "NSPEPI and check_invalid_config tools can be run on the CentOS and Ubuntu systems" - "If python3 is installed, then please create a symbolic link for python like "ln -s /usr/bin/pytho3 /usr/bin/python".

The correct command should be "ln -s /usr/bin/python3 /usr/bin/python"

**Comment by Aman-Agrawal1** [comment]
Fixed the typo.
