### ISSUE TITLE
Unable to run "check_invalid_config" getting Syntax arguments

### ISSUE THREAD

**Issue by redred623** [netscaler/ADC-scripts#21]
Good afternoon:

I am working to update our citrix ADC to version 14.1, we are on version 13.0 and I know we are out of support and I am wanting to get us to 13.1 ASAP. I have git pulled all the files in the repo and moved them over to the ADC but I am getting an error no matter how I run it. I am just simply running: **check_invalid_config /nsconfig/ns.conf -buildVersion 13.1** and I get: 

```
usage: configCheck [-h] -f <path to ns config file> [-v] [-V]
configCheck: error: unrecognized arguments: -B 13.1
Error in checking config file: 512root@DalNetScalerLB#

```
Not matter what I do it will not work. I really want to run the pre-check before the upgrade and the nspepi tool is working so I am unsure what the issue is here. Any help would be apprecitated.

**Comment by redred623** [comment]
I would like to add I have ran the bash nspepi_install_script command and continue to see the same issue. 

`check_invalid_config /nsconfig/ns.conf
usage: configCheck [-h] -f <path to ns config file> [-v] [-V]
configCheck: error: unrecognized arguments: -B 13.1
`

**Comment by Aman-Agrawal1** [comment]
Hi @redred623 , I'm not able to reproduce the issue.

root@ns# cp check_invalid_config nspepi nspepi_install_script /netscaler/
root@ns# cd nspepi2/
root@ns# ls
check_classic_configs.py        config_check_main.py            convert_cmp_cmd.py              convert_responder_command.py    nspepi_main.py
check_classic_expr.py           convert_auth_cmd.py             convert_filter_command.py       convert_rewrite_command.py      nspepi_parse_tree.py
cli_lex.py                      convert_classic_expr.py         convert_lb_cmd.py               nspepi_common.py                pi_lex.py
cli_yacc.py                     convert_cli_commands.py         convert_patclass_commands.py    nspepi_helper
root@ns# cp * /netscaler/nspepi2/
root@ns# cd /netscaler/
root@ns# bash nspepi_install_script
Copying the files to /var/nspepi_backup as a backup
Installation successful
root@ns#
root@ns# check_invalid_config /nsconfig/ns.conf -buildVersion 13.1

No invalid or deprecated config detected with the configuration.

Use pre-validation tool and nspepi tool available at https://github.com/citrix/ADC-scripts/tree/master/nspepi for the most complete and up-to-date version.
root@ns#


Can you please share the "config_check_main.py" file present in /netscaler/nspepi2 directory?

**Comment by redred623** [comment]
root@DalNetScalerLB# ls
root@DalNetScalerLB# cd netscaler
root@DalNetScalerLB# cp check_invalid_config nspepi nspepi_install_script /netscaler/
cp: /netscaler/nspepi_install_script and nspepi_install_script are identical (not copied).
cp: /netscaler/nspepi and nspepi are identical (not copied).
cp: /netscaler/check_invalid_config and check_invalid_config are identical (not copied).
root@DalNetScalerLB# cd nspepi2/
root@DalNetScalerLB# ls
check_classic_configs.py        cli_lex.py                      config_check_main.py            convert_cmp_cmd.py              convert_responder_command.py    nspepi_helper                   pi_lex.py
check_classic_configs.pyc       cli_lex.pyc                     convert_auth_cmd.py             convert_filter_command.py       convert_rewrite_command.py      nspepi_main.py
check_classic_expr.py           cli_yacc.py                     convert_classic_expr.py         convert_lb_cmd.py               nspepi_common.py                nspepi_parse_tree.py
check_classic_expr.pyc          cli_yacc.pyc                    convert_cli_commands.py         convert_patclass_commands.py    nspepi_common.pyc               nspepi_parse_tree.pyc
root@DalNetScalerLB# cp * /netscaler/nspepi2/
cp: /netscaler/nspepi2/check_classic_configs.py and check_classic_configs.py are identical (not copied).
cp: /netscaler/nspepi2/nspepi_parse_tree.pyc and nspepi_parse_tree.pyc are identical (not copied).
cp: /netscaler/nspepi2/nspepi_parse_tree.py and nspepi_parse_tree.py are identical (not copied).
cp: /netscaler/nspepi2/nspepi_main.py and nspepi_main.py are identical (not copied).
cp: /netscaler/nspepi2/nspepi_helper and nspepi_helper are identical (not copied).
cp: /netscaler/nspepi2/nspepi_common.pyc and nspepi_common.pyc are identical (not copied).
cp: /netscaler/nspepi2/nspepi_common.py and nspepi_common.py are identical (not copied).
cp: /netscaler/nspepi2/convert_rewrite_command.py and convert_rewrite_command.py are identical (not copied).
cp: /netscaler/nspepi2/convert_responder_command.py and convert_responder_command.py are identical (not copied).
cp: /netscaler/nspepi2/convert_patclass_commands.py and convert_patclass_commands.py are identical (not copied).
cp: /netscaler/nspepi2/convert_lb_cmd.py and convert_lb_cmd.py are identical (not copied).
cp: /netscaler/nspepi2/convert_filter_command.py and convert_filter_command.py are identical (not copied).
cp: /netscaler/nspepi2/convert_cmp_cmd.py and convert_cmp_cmd.py are identical (not copied).
cp: /netscaler/nspepi2/convert_cli_commands.py and convert_cli_commands.py are identical (not copied).
cp: /netscaler/nspepi2/convert_classic_expr.py and convert_classic_expr.py are identical (not copied).
cp: /netscaler/nspepi2/convert_auth_cmd.py and convert_auth_cmd.py are identical (not copied).
cp: /netscaler/nspepi2/config_check_main.py and config_check_main.py are identical (not copied).
cp: /netscaler/nspepi2/cli_yacc.pyc and cli_yacc.pyc are identical (not copied).
cp: /netscaler/nspepi2/cli_yacc.py and cli_yacc.py are identical (not copied).
cp: /netscaler/nspepi2/cli_lex.pyc and cli_lex.pyc are identical (not copied).
cp: /netscaler/nspepi2/cli_lex.py and cli_lex.py are identical (not copied).
cp: /netscaler/nspepi2/check_classic_expr.pyc and check_classic_expr.pyc are identical (not copied).
cp: /netscaler/nspepi2/check_classic_expr.py and check_classic_expr.py are identical (not copied).
cp: /netscaler/nspepi2/check_classic_configs.pyc and check_classic_configs.pyc are identical (not copied).
cp: /netscaler/nspepi2/pi_lex.py and pi_lex.py are identical (not copied).
root@DalNetScalerLB# cd /netscaler/
root@DalNetScalerLB# bash nspepi_install_script
Copying the files to /var/nspepi_backup as a backup
Installation successful
root@DalNetScalerLB# **check_invalid_config /nsconfig/ns.conf -buildVersion 13.1**
usage: configCheck [-h] -f <path to ns config file> [-v] [-V]
configCheck: error: unrecognized arguments: -B 13.1
Error in checking config file: 512root@DalNetScalerLB#

**Comment by redred623** [comment]
Here is the contents of the file you requested. 
```
#!/usr/bin/env python

# Copyright 2021 Citrix Systems, Inc. All rights reserved.
# This software and documentation contain valuable trade
# secrets and proprietary property belonging to Citrix Systems, Inc.
# None of this software and documentation may be copied,
# duplicated or disclosed without the express
# written permission of Citrix Systems, Inc.

"""
Checks whether config file contains invalid
epressions and features.

Dependency packages: PLY, pytest
"""

# Ensure that the version string conforms to PEP 440:
# https://www.python.org/dev/peps/pep-0440/
__version__ = "1.0"

import re
import argparse
import glob
import importlib
import logging
import logging.handlers
import os
import os.path
import sys
from inspect import cleandoc
import inspect

import cli_yacc
import nspepi_common as common

import check_classic_configs

# Log handlers that need to be saved from call to call
file_log_handler = None
console_log_handler = None


def setup_logging(log_file_name, file_log_level):
    """
    Sets up logging for the program.

    Args:
        log_file_name: The name of the log file
        file_log_level: The level of logs to put in the file log
    """
    global file_log_handler
    global console_log_handler
    # create logger
    logger = logging.getLogger()
    logger.setLevel(logging.DEBUG)
    # if called multiple times, remove existing handlers
    logger.removeHandler(file_log_handler)
    logger.removeHandler(console_log_handler)
    # create file handler and roll logs if needed
    exists = os.path.isfile(log_file_name)
    file_log_handler = logging.handlers.RotatingFileHandler(log_file_name,
                                                            mode='a',
                                                            backupCount=9)
    if exists:
        file_log_handler.doRollover()
    # set the file log handler level
    file_log_handler.setLevel(file_log_level)
    # create console handler that sees even info messages
    console_log_handler = logging.StreamHandler()
    console_log_handler.setLevel(logging.INFO)
    # create formatters and add them to the handlers
    fh_format = logging.Formatter('%(asctime)s: %(levelname)s - %(message)s')
    ch_format = logging.Formatter('%(levelname)s - %(message)s')
    file_log_handler.setFormatter(fh_format)
    console_log_handler.setFormatter(ch_format)
    # add the handlers to the logger
    logger.addHandler(file_log_handler)
    logger.addHandler(console_log_handler)


def output_line(line, outfile, verbose):
    """
    Output a (potentially) converted line.

    Args:
        line: the line to output
        outfile: Output file to write converted commands
        verbose: True iff converted commands should also be output to console
    """
    outfile.write(line)
    if verbose:
        logging.info(line.rstrip())


def check_for_removed_expression(cmd, outfile, verbose):
    """
    Checks for the expressions which are removed.
    Args:
        cmd: NS config command to be checked
        outfile: Output file to write commands using removed config
        verbose: True iff converted commands should also be output to console
    """
    if re.search(r'\bSYS\s*\.\s*EVAL_CLASSIC_EXPR\s*\(',
                 cmd, re.IGNORECASE):
        output_line(cmd, outfile, verbose)
        return

    body_expr = re.compile(r'\bHTTP\s*\.\s*REQ\s*\.\s*BODY\b\s*', re.IGNORECASE)
    cmd_len = len(cmd)
    for match in re.finditer(body_expr, cmd):
        start_index = match.start()
        length = match.end() - match.start()
        if (((start_index + length) >= cmd_len) or
             (cmd[start_index + length] != '(')):
            output_line(cmd, outfile, verbose)
            return

    if re.search(r'\b((Q\.HOSTNAME)|(Q\.TRACKING)|'
                 '(Q\.METHOD)|(Q\.URL)|(Q\.VERSION)|'
                 '(Q\.CONTENT_LENGTH)|(Q\.HEADER)|'
                 '(Q\.IS_VALID)|(Q\.DATE)|'
                 '(Q\.COOKIE)|(Q\.BODY)|(Q\.TXID)|'
                 '(Q\.CACHE_CONTROL)|(Q\.USER)|'
                 '(Q\.IS_NTLM_OR_NEGOTIATE)|'
                 '(Q\.FULL_HEADER)|'
                 '(Q\.LB_VSERVER)|(Q\.CS_VSERVER))',
                 cmd, re.IGNORECASE):
        output_line(cmd, outfile, verbose)
        return

    if re.search(r'\b((S\.VERSION)|(S\.STATUS)|'
                  '(S\.STATUS_MSG)|(S\.IS_REDIRECT)|'
                  '(S\.IS_INFORMATIONAL)|(S\.IS_SUCCESSFUL)|'
                  '(S\.IS_CLIENT_ERROR)|(S\.IS_SERVER_ERROR)|'
                  '(S\.TRACKING)|(S\.HEADER)|(S\.FULL_HEADER)|'
                  '(S\.IS_VALID)|(S\.DATE)|(S\.BODY)|'
                  '(S\.SET_COOKIE)|(S\.SET_COOKIE2)|'
                  '(S\.CONTENT_LENGTH)|'
                  '(S\.CACHE_CONTROL)|(S\.TXID)|(S\.MEDIA))',
                  cmd, re.IGNORECASE):
        output_line(cmd, outfile, verbose)
        return


def check_config_file(infile, outfile, verbose):
    """
    Process ns config file passed in argument and report the classic and
    removed commands.

    Args:
        infile: NS config file to be converted
        outfile: Output file to write commands using removed config
        verbose: True iff converted commands should also be output to console
    """
    cli_yacc.cli_yacc_init()
    # Register handler methods for various commands
    currentfile = os.path.abspath(inspect.getfile(inspect.currentframe()))
    currentdir = os.path.dirname(currentfile)
    for module in glob.glob(os.path.join(currentdir, 'check_classic_configs.py')):
        importlib.import_module(os.path.splitext(os.path.basename(module))[0])
    # call methods registered to be called before the start of processing
    # config file.
    for m in common.init_methods:
        m.method(m.obj)
    lineno = 0
    for cmd in infile:
        lineno += 1
        parsed_tree = cli_yacc.cli_yacc_parse(cmd, lineno)
        if parsed_tree is not None:
            # construct dictionary key to look up registered method to call to
            # parse and transform the command to be emitted
            # Registered method can return either string or tree.
            key = " ".join(parsed_tree.get_command_type()).lower()
            if key in common.dispatchtable:
                for m in common.dispatchtable[key]:
                    # Since, we are only checking the config and not
                    # converting to advanced, so list will contains
                    # at most only one command.
                    output = m.method(m.obj, parsed_tree)
                    if len(output) == 0:
                        check_for_removed_expression(cmd, outfile, verbose)
                    else:
                         output_line(cmd, outfile, verbose)
            else:
                check_for_removed_expression(cmd, outfile, verbose)
        else:
            check_for_removed_expression(cmd, outfile, verbose)


def main():
    desc = cleandoc(
        """
        Checks whether invalid config is present in input file
        """)
    arg_parser = argparse.ArgumentParser(
        prog="configCheck",
        description=desc,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    arg_parser.add_argument(
        "-f", "--infile", metavar="<path to ns config file>",
        help="Checks whether invalid config is present in the input file",
        required=True)
    arg_parser.add_argument(
        "-v", "--verbose", action="store_true", help="show verbose output")
    arg_parser.add_argument(
        '-V', '--version', action='version',
        version='%(prog)s {}'.format(__version__))
    try:
        args = arg_parser.parse_args()
    except IOError as e:
        exit(str(e))
    # obtain logging parameters and setup logging
    conf_file_path = os.path.dirname(args.infile)
    conf_file_name = os.path.basename(args.infile)
    check_classic_configs.check_configs_init()
    new_path = os.path.join(conf_file_path, "issues_" + conf_file_name)
    with open(args.infile, 'r') as infile:
        with open(new_path, 'w') as outfile:
            check_config_file(infile, outfile, args.verbose)


if __name__ == '__main__':
    main()

```

**Comment by redred623** [comment]
I appreciate the help here. I just compared that file in my system to the branch and it was off, not sure how that happened. I did pull the files using a git clone but I guess it pulled an older file. I just manually added the file in question and it worked for me. I am good to call this resolved and I appreciate your help

**Comment by redred623** [comment]
File in my system was not correct and needed to be updated
