### ISSUE TITLE
authorization policies are NOT converted if nspepi should convert a whole config file

### ISSUE THREAD

**Issue by hnmr** [netscaler/ADC-scripts#6]
Hello,

while this syntax works fine:
./nspepi -e 'REQ.IP.DESTIP == 10.10.10.0 -netmask 255.255.255.0'
"CLIENT.IP.DST.IN_SUBNET(10.10.10.0/24)"

the processing of the config file does NOT convert authorization policies:

$ cat test.conf
add authorization policy LAN_10 "REQ.IP.DESTIP == 10.10.10.0 -netmask 255.255.255.0" ALLOW
$ ./nspepi -f test.conf -v
INFO - add authorization policy LAN_10 "REQ.IP.DESTIP == 10.10.10.0 -netmask 255.255.255.0" ALLOW

Converted config will be available in a new file new_test.conf.
Check warn_test.conf file for any warnings or errors that might have been generated.
$ cat new_test.conf
add authorization policy LAN_10 "REQ.IP.DESTIP == 10.10.10.0 -netmask 255.255.255.0" ALLOW
$ wc -l warn_test.conf
0 warn_test.conf

Please advise. Thank you!
BR
Hermann M.

**Comment by geethapinnaka** [comment]
Authorization policy conversion is not supported by the tool. Please check https://github.com/geethapinnaka/ADC-scripts/blob/master/nspepi/README.md#commands-or-features-handled-by-the-nspepi-conversion-tool for the conversions that we support.
Please work with the support team if you need any help in converting Authorization policies.

**Comment by Aman-Agrawal1** [comment]
@hnmr , can we close this issue?

**Comment by hnmr** [comment]
No comments
